networks:
  cosmocam-network:
    external: true

services:
  cosmocam:
    image: ahclemen/cosmocam:latest
    build:
      context: .
      dockerfile: ./docker/main/Dockerfile
    ports:
      - "443:3001"
      # - "2000-2100:2000-2100/tcp"
      # - "2000-2100:2000-2100/udp"
    networks:
      cosmocam-network:
        ipv4_address: 172.18.0.3
    links:
      - "db:database"
    env_file:
      - packages/cosmocam-backend/.env
    # expose:
    #   - "2000-2100/tcp"
    #   - "2000-2100/udp"

  mediaserver:
    image: ahclemen/cosmocam-mediaserver:latest
    build:
      context: .
      dockerfile: ./docker/mediaserver/Dockerfile
    ports:
      - "3002:3002"
      - "2000-2100:2000-2100/tcp"
      - "2000-2100:2000-2100/udp"
    networks:
      cosmocam-network:
        ipv4_address: 172.18.0.4
    links:
      - "db:database"
    env_file:
      - packages/cosmocam-backend/.env
    expose:
      - "2000-2100/tcp"
      - "2000-2100/udp"

  db:
    image: mongo:4.4.18
    ports:
      - "2717:27017"
    networks:
      cosmocam-network:
        ipv4_address: 172.18.0.2
