networks:
  cosmocam-network:
    external: true

services:
  nginx:
    image: ahclemen/cosmocam-nginx:latest
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "443:443"
    networks:
      cosmocam-network:
        ipv4_address: 172.18.0.5
    volumes:
      - ./packages/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./packages/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl/cert.pem:/etc/nginx/ssl/live/localhost/cert.pem
      - ./ssl/key.pem:/etc/nginx/ssl/live/localhost/key.pem

  cosmocam:
    image: ahclemen/cosmocam:latest
    build:
      context: .
      dockerfile: ./docker/main/Dockerfile
    networks:
      cosmocam-network:
        ipv4_address: 172.18.0.3
    links:
      - "db:database"
    env_file:
      - .env

  mediaserver:
    image: ahclemen/cosmocam-mediaserver:latest
    build:
      context: .
      dockerfile: ./docker/mediaserver/Dockerfile
    ports:
      - "2000-2100:2000-2100/tcp"
      - "2000-2100:2000-2100/udp"
    networks:
      cosmocam-network:
        ipv4_address: 172.18.0.4
    env_file:
      - .env

  db:
    image: mongo:4.4.18
    networks:
      cosmocam-network:
        ipv4_address: 172.18.0.2
