FROM node:18 
# AS stage-one

# Install DEB dependencies and others.
RUN \
	set -x \
	&& apt-get update \
	&& apt-get install -y net-tools build-essential python3 python3-pip valgrind

WORKDIR /cosmocam-monorepo

COPY . /cosmocam-monorepo

RUN yarn install
RUN cd packages/shared && tsc
RUN cd ../cosmocam-frontend && yarn build
RUN cd ../cosmocam-backend && NODE_ENV=production

CMD ["node", "./packages/cosmocam-backend/dist/server.js"]